packages:
  - 'packages/*'
  - 'examples/*'

catalog:
  # Build Tools & Bundlers
  vite: ^7.3.0
  tsup: ^8.5.1
  
  # TypeScript & Types
  typescript: ^5.9.3
  "@types/node": ^25.0.3
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  
  # Framework Plugins
  "@vitejs/plugin-vue": ^6.0.3
  "@vitejs/plugin-react": ^5.1.2
  "@sveltejs/vite-plugin-svelte": ^3.1.2
  "vite-plugin-solid": ^2.11.0
  "@preact/preset-vite": ^2.8.2
  
  # Development Tools
  vite-plugin-vue-devtools: ^8.0.5
  vite-plugin-pwa: ^1.2.0
  vite-plugin-cdn-import: ^1.0.1
  vite-plugin-cache: ^1.4.8
  rollup-plugin-visualizer: ^6.0.5
  
  # Validation & Utilities
  zod: ^4.2.1
  
  # Compression
  tar: ^7.4.3
  archiver: ^7.0.1
  "@types/tar": ^6.1.13
  "@types/archiver": ^6.0.3
  
  # Framework Libraries
  vue: ^3.5.26
  react: ^19.2.3
  react-dom: ^19.2.3
  
  # Development Dependencies
  "@changesets/cli": ^2.29.8
  eslint: ^9.39.2
  prettier: ^3.7.4
  glob: ^13.0.0
  js-yaml: ^4.1.1
  rimraf: ^6.0.1